name: mentorship
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^7.0.1
  http: ^1.6.0
  shared_preferences: ^2.5.4
  image_picker: ^1.2.1
  intl: ^0.20.2
  firebase_messaging: ^16.1.0
  flutter_local_notifications: ^19.5.0
  file_picker: ^10.3.8
  url_launcher: ^6.3.2
  cloudinary_public: ^0.23.1
  video_player: ^2.10.1
  chewie: ^1.13.0
  flutter_cached_pdfview: ^0.4.3
  firebase_core: ^4.3.0
  cloud_firestore: ^6.1.1
  flutter_pdfview: ^1.4.4
  path_provider: ^2.1.5
  firebase_auth: ^6.1.3
  flutter_launcher_icons: ^0.14.4
  youtube_player_flutter: ^9.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

# Icon Configuration (Bilkul Sahi Hai)
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.jpg"
  min_sdk_android: 21